### ISSUE TITLE
All Work Features 

### ISSUE THREAD

**Issue by jonaslee228** [lf-/ShortcutItPy#1]
Hey you should create a shortcut feature with a turn on and off all work features. 
That would be a very handy tool to have. Let me know if you could at all. thanks a lot for this addin its is amazing.

**Comment by lf-** [comment]
Please indicate what the built in Fusion command is for this, as well as
what it does. I can't quite picture what you're aiming for.

I don't have the development resources available to add functionality and
it is currently beyond the scope of the project to actually add features
and functionality rather than simply expose what is in Fusion already.

**Comment by jonaslee228** [comment]
Here is what im am talking about. If there would be a option to turn this on and off.

![Screenshot (16)_LI](https://user-images.githubusercontent.com/47899193/56900178-33826180-6a63-11e9-93d5-12c6c47c883f.jpg)

![Screenshot (15)](https://user-images.githubusercontent.com/47899193/56900185-3a10d900-6a63-11e9-84d3-35a2b825b1ae.png)

**Comment by lf-** [comment]
Oh, cool. If you can find the API to actually do that, that would be fantastic and I would consider adding it; there's a skeleton of a new command available on the new command branch. Unfortunately there's a lot of these user interface things which don't have any API exposed, for instance selection filters (it's Autodesk internal API and I don't have the debug symbols to semi safely but sinfully call it across versions).

**Comment by jonaslee228** [comment]
Also there is another feature i was wondering about. Is there a way to have a shortcut/option to "activate all".Like i have shown here. 

![Screenshot (17)_LI](https://user-images.githubusercontent.com/47899193/56900421-cf13d200-6a63-11e9-9ecc-88765b9b7fe0.jpg)

**Comment by lf-** [comment]
To be clear, I'm saying there might be API for this but I haven't looked.

**Comment by lf-** [comment]
As for "activate all", that might be doable, assuming there is a command for it already. Is there a specific activate all command?

I think it's probably possible to automatically select the top level component and then activate it ourselves, but again that's in the realm of making a new command, which I currently don't have the resources to do.

**Comment by jonaslee228** [comment]
I am not sure if there is or not. I couldn't find anything. But then again i dont know much about this. (on the programming side)

**Comment by burakkuvvetli** [comment]
hi, 
Couldnt make it work. can you explain hot to install this?

thanks

**Comment by lf-** [comment]
My mistake. I thought I had documented that. See https://knowledge.autodesk.com/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/How-to-install-an-ADD-IN-and-Script-in-Fusion-360.html

To actually get the add in code, use the big green download button in the top right of the code tab on this repository and download a zip file.

**Comment by burakkuvvetli** [comment]
Thank you, it worked. And i have a request from you if its not a big deal, adding "find in windows" to the options to focus on an object in the viewport. I use it a lot and selecting it from the dropdown menu it slows me so much.

**Comment by lf-** [comment]
Sounds doable. I've documented the procedure to add a new command in the README on this repository, and I would happily accept a pull request for adding that command once you've gotten it working.

**Comment by lf-** [comment]
@burakkuvvetli so I actually tried this, and Fusion gets major level confused and deletes the Find In Browser command when you add Find in Window to this menu. I have absolutely no idea why this is possibly happening.

**Comment by burakkuvvetli** [comment]
sad to hear that. maybe we have to wait for the fusion team to add this option. 
anyway, thanks for the effort!

**Comment by lf-** [comment]
@burakkuvvetli so I played around with it today and can get both to show up. I think what was happening is that you need to open a context menu showing the "find in browser" or "find in window" commands for them to show up in my menu. I'm 99% sure this is not my doing.
