### ISSUE TITLE
Reset orbit center

### ISSUE THREAD

**Issue by CatalystProjectLab** [lf-/ShortcutItPy#2]
could you include a reset orbit center?, i believe it's not the same as set orbit center

thanks

**Comment by lf-** [comment]
The process for adding commands is documented in the README on the home page of this repository. I would be glad to assist you if you have any questions about the process.

**Comment by lf-** [comment]
Added since I had to do other maintenance work. For future additions, I strongly encourage submitting a pull request as features submitted as pull requests will probably get added within 24h.
