### ISSUE TITLE
Add Look At

### ISSUE THREAD

**Issue by Huffster** [lf-/ShortcutItPy#4]
Hello,
Thanks for all of your work on the Shortcut add-in for F360.
I attempted to add the "Look At" function to the code but failed miserably.
Is it possible to add this to the drop down?
Thanks!
Ricky

**Comment by lf-** [comment]
Hi! I'd love to add it but Fusion doesn't work on my main computer anymore 🙃

Is Look At listed in the list from DumpCmdDefs?

**Comment by Huffster** [comment]
Thanks so much for getting back to me!
I am a total noob, how do I determine if LookAt is in the DumpCmdDefs?
Thanks,
Ricky


Ricky Huff (he/him/his)
Mechanical Engineering Technical Lead

Synapse Product Development
A Cambridge Consultants Company
mail 1511 6th Ave Suite 400, Seattle, WA 98101
direct +1 206 832 1269 ext. 4626<tel:+1%20206%20832%201269,4626> | office +1 206 381 0898<tel:+1%20206%20381%200898> | mobile +1 760 953 0069<tel:+1%20760%20953%200069>
ricky.huff@synapse.com<mailto:ricky.huff@synapse.com> | https://www.synapse.com<https://www.synapse.com/>

This email and any files transmitted with it are confidential. Unauthorized publication, use or dissemination of this email is prohibited.
Please consider the environment before printing.

________________________________

**Comment by lf-** [comment]
When you install and run the DumpCmdDefs script from this repository, it will ask you to save a txt file that has all the internal command names fusion uses. Open that saved file in notepad and use the search function to find "Look" and look through the results for what looks like the right command. It's probably LookAt unless they initially called it something else and didn't rename it, but you never know. 

You can then install this extension if you haven't already, and edit the Python file by clicking on the appropriate button in the extensions list box and try to add the command to the list. Stop and start the extension and see if it's worked.
